"""
Script de peuplement de données de démonstration.
Exécuter : python seed_data.py
"""
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'agridata.settings')
django.setup()

from datetime import date, timedelta
from collecte.models import FicheElevage
import random

FicheElevage.objects.all().delete()

donnees = [
    dict(date_collecte=date.today()-timedelta(days=1),  nom_eleveur="Jean-Pierre Mballa",    localite="Mimboman",    region="Centre",    espece="poulet",  systeme_elevage="intensif",       effectif_total=500, effectif_males=120, effectif_femelles=380, age_moyen=3.5,  poids_moyen=1.8,  etat_sante="bon",       taux_mortalite=2.5,  production_journaliere=320, alimentation="Aliment complet ponte",   superficie_m2=200, vaccination=True,  type_vaccin="Newcastle, Gumboro", maladies_observees="",             cout_alimentation_mensuel=75000,  revenu_mensuel_estime=180000, observations="Élevage en bon état général."),
    dict(date_collecte=date.today()-timedelta(days=3),  nom_eleveur="Marie Ateba",            localite="Obala",       region="Centre",    espece="canard",  systeme_elevage="semi_intensif",  effectif_total=200, effectif_males=60,  effectif_femelles=140, age_moyen=5.0,  poids_moyen=2.4,  etat_sante="excellent", taux_mortalite=1.0,  production_journaliere=90,  alimentation="Son de blé + maïs",       superficie_m2=150, vaccination=True,  type_vaccin="Influenza aviaire",   maladies_observees="",             cout_alimentation_mensuel=40000,  revenu_mensuel_estime=120000, observations="Très bon rendement."),
    dict(date_collecte=date.today()-timedelta(days=5),  nom_eleveur="Paul Essomba",           localite="Soa",         region="Centre",    espece="porc",    systeme_elevage="semi_intensif",  effectif_total=80,  effectif_males=20,  effectif_femelles=60,  age_moyen=8.0,  poids_moyen=65.0, etat_sante="bon",       taux_mortalite=3.0,  production_journaliere=0,   alimentation="Déchets + provende",      superficie_m2=300, vaccination=True,  type_vaccin="Rouget, PPC",        maladies_observees="Gale légère",  cout_alimentation_mensuel=90000,  revenu_mensuel_estime=250000, observations="Traitement gale en cours."),
    dict(date_collecte=date.today()-timedelta(days=7),  nom_eleveur="Cécile Ngo Biyong",      localite="Yaoundé",     region="Centre",    espece="caille",  systeme_elevage="intensif",       effectif_total=1200,effectif_males=400, effectif_femelles=800, age_moyen=2.0,  poids_moyen=0.18, etat_sante="excellent", taux_mortalite=0.5,  production_journaliere=700, alimentation="Aliment caille spécial",  superficie_m2=80,  vaccination=False, type_vaccin="",                    maladies_observees="",             cout_alimentation_mensuel=35000,  revenu_mensuel_estime=140000, observations="Production d'œufs excellente."),
    dict(date_collecte=date.today()-timedelta(days=10), nom_eleveur="Thomas Nkoa",            localite="Mbalmayo",    region="Centre",    espece="ovin",    systeme_elevage="extensif",       effectif_total=45,  effectif_males=15,  effectif_femelles=30,  age_moyen=18.0, poids_moyen=28.0, etat_sante="moyen",     taux_mortalite=5.0,  production_journaliere=0,   alimentation="Pâturage naturel",        superficie_m2=5000,vaccination=False, type_vaccin="",                    maladies_observees="Parasites intest.",cout_alimentation_mensuel=8000,   revenu_mensuel_estime=60000,  observations="Déparasitage nécessaire."),
    dict(date_collecte=date.today()-timedelta(days=12), nom_eleveur="Suzanne Fouda",          localite="Douala",      region="Littoral",  espece="poulet",  systeme_elevage="intensif",       effectif_total=2000,effectif_males=200, effectif_femelles=1800,age_moyen=4.0,  poids_moyen=2.1,  etat_sante="bon",       taux_mortalite=1.8,  production_journaliere=1400,alimentation="Aliment ponte industriel", superficie_m2=600, vaccination=True,  type_vaccin="Newcastle + Marek",   maladies_observees="",             cout_alimentation_mensuel=280000, revenu_mensuel_estime=700000, observations="Grande exploitation commerciale."),
    dict(date_collecte=date.today()-timedelta(days=15), nom_eleveur="Alain Beyala",           localite="Bafoussam",   region="Ouest",     espece="lapin",   systeme_elevage="intensif",       effectif_total=300, effectif_males=100, effectif_femelles=200, age_moyen=4.0,  poids_moyen=2.8,  etat_sante="bon",       taux_mortalite=4.0,  production_journaliere=0,   alimentation="Herbes + aliment lapin",  superficie_m2=120, vaccination=True,  type_vaccin="Myxomatose, VHD",    maladies_observees="",             cout_alimentation_mensuel=25000,  revenu_mensuel_estime=90000,  observations="Reproduction régulière."),
    dict(date_collecte=date.today()-timedelta(days=18), nom_eleveur="Hélène Manga",           localite="Garoua",      region="Nord",      espece="bovin",   systeme_elevage="extensif",       effectif_total=120, effectif_males=30,  effectif_femelles=90,  age_moyen=36.0, poids_moyen=320.0,etat_sante="excellent", taux_mortalite=0.8,  production_journaliere=180, alimentation="Pâturage + complément",   superficie_m2=50000,vaccination=True,  type_vaccin="PPCB, Charbon",      maladies_observees="",             cout_alimentation_mensuel=150000, revenu_mensuel_estime=600000, observations="Troupeau Goudali bien géré."),
    dict(date_collecte=date.today()-timedelta(days=20), nom_eleveur="Roger Eto'o",            localite="Ngaoundéré",  region="Adamaoua",  espece="caprin",  systeme_elevage="extensif",       effectif_total=85,  effectif_males=20,  effectif_femelles=65,  age_moyen=14.0, poids_moyen=22.0, etat_sante="moyen",     taux_mortalite=6.0,  production_journaliere=25,  alimentation="Pâturage libre",          superficie_m2=8000,vaccination=False, type_vaccin="",                    maladies_observees="PPR suspecté",  cout_alimentation_mensuel=5000,   revenu_mensuel_estime=45000,  observations="Consultation vétérinaire urgente."),
    dict(date_collecte=date.today()-timedelta(days=22), nom_eleveur="Christine Owono",        localite="Ebolowa",     region="Sud",       espece="dinde",   systeme_elevage="semi_intensif",  effectif_total=150, effectif_males=40,  effectif_femelles=110, age_moyen=6.0,  poids_moyen=7.5,  etat_sante="bon",       taux_mortalite=3.5,  production_journaliere=60,  alimentation="Maïs concassé + son",     superficie_m2=400, vaccination=True,  type_vaccin="Newcastle",           maladies_observees="",             cout_alimentation_mensuel=55000,  revenu_mensuel_estime=180000, observations="Bonne croissance."),
    dict(date_collecte=date.today()-timedelta(days=25), nom_eleveur="Fabrice Ndzana",         localite="Bertoua",     region="Est",       espece="poulet",  systeme_elevage="extensif",       effectif_total=80,  effectif_males=30,  effectif_femelles=50,  age_moyen=5.0,  poids_moyen=1.5,  etat_sante="moyen",     taux_mortalite=8.0,  production_journaliere=30,  alimentation="Maïs + déchets ménagers", superficie_m2=500, vaccination=False, type_vaccin="",                    maladies_observees="Bronchite infectieuse",cout_alimentation_mensuel=12000, revenu_mensuel_estime=35000,  observations="Amélioration du système recommandée."),
    dict(date_collecte=date.today()-timedelta(days=30), nom_eleveur="Nadège Tchoua",          localite="Kribi",       region="Sud",       espece="pigeon",  systeme_elevage="semi_intensif",  effectif_total=500, effectif_males=250, effectif_femelles=250, age_moyen=8.0,  poids_moyen=0.45, etat_sante="excellent", taux_mortalite=0.5,  production_journaliere=40,  alimentation="Grain + minéraux",        superficie_m2=60,  vaccination=False, type_vaccin="",                    maladies_observees="",             cout_alimentation_mensuel=18000,  revenu_mensuel_estime=75000,  observations="Pigeons voyageurs + chair."),
]

for d in donnees:
    FicheElevage.objects.create(**d)

print(f"✅ {len(donnees)} fiches de démonstration créées avec succès!")
